### ISSUE TITLE
ITK fails to build on GCC 13

### ISSUE THREAD

**Issue by oceanusxiv** [educelab/vc-deps#7]
The issue is described here https://discourse.itk.org/t/building-itk-error-with-algorithim-module/5927/8. It's been fixed by the latest release, but since our dep is still pulling 5.3.0 we don't have access to that change.

The fix can be as simple as applying this commit
https://github.com/InsightSoftwareConsortium/ITK/commit/9a719a0d2f5f489eeb9351b0ef913c3693147a4f
as a patch.

**Comment by csparker247** [comment]
Thanks for reporting. The fix is available in #8, but since ITK 5.4 is still in RC status, I'm going to wait to merge it. In the meantime, you can checkout the `7-fix-itk-gcc13` branch when you do your vc-deps builds.

Edit: ITK 5.4 is scheduled for release towards the end of February: https://github.com/InsightSoftwareConsortium/ITK/milestone/19

**Comment by csparker247** [comment]
Seems like ITK 5.4 is still pending release, now listed for April 19th, 2024. We'll see.
